export enum ApiChatType {
  PRIVATE = 'PRIVATE',
  GROUP = 'GROUP',
  SUPERGROUP = 'SUPERGROUP',
  CHANNEL = 'CHANNEL',
  COMMUNITY = 'COMMUNITY',
  BROADCAST = 'BROADCAST',
  FORUM = 'FORUM',
}

export enum ApiChatRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  MEMBER = 'MEMBER',
  SUBSCRIBER = 'SUBSCRIBER',
}

export enum ApiMessageType {
  // Медиа сообщения
  PHOTO = 'PHOTO',
  VIDEO_MESSAGE = 'VIDEO_MESSAGE',
  VOICE_MESSAGE = 'VOICE_MESSAGE',
  VIDEO_NOTE = 'VIDEO_NOTE',
  ANIMATION = 'ANIMATION',

  // Документы и файлы
  DOCUMENT = 'DOCUMENT',
  AUDIO = 'AUDIO',

  // Интерактивные элементы
  POLL = 'POLL',
  QUIZ = 'QUIZ',
  DICE = 'DICE',
  DART = 'DART',
  BASKETBALL = 'BASKETBALL',
  FOOTBALL = 'FOOTBALL',
  CASINO = 'CASINO',
  BOWLING = 'BOWLING',

  // Местоположение и контакты
  LOCATION = 'LOCATION',
  LIVE_LOCATION = 'LIVE_LOCATION',
  VENUE = 'VENUE',
  CONTACT = 'CONTACT',

  // Платежи и коммерция
  INVOICE = 'INVOICE',
  SUCCESSFUL_PAYMENT = 'SUCCESSFUL_PAYMENT',

  // Системные и служебные
  NEW_CHAT_MEMBERS = 'NEW_CHAT_MEMBERS',
  LEFT_CHAT_MEMBER = 'LEFT_CHAT_MEMBER',
  NEW_CHAT_TITLE = 'NEW_CHAT_TITLE',
  NEW_CHAT_PHOTO = 'NEW_CHAT_PHOTO',
  DELETE_CHAT_PHOTO = 'DELETE_CHAT_PHOTO',
  GROUP_CHAT_CREATED = 'GROUP_CHAT_CREATED',
  SUPERGROUP_CHAT_CREATED = 'SUPERGROUP_CHAT_CREATED',
  CHANNEL_CHAT_CREATED = 'CHANNEL_CHAT_CREATED',
  MIGRATE_TO_CHAT_ID = 'MIGRATE_TO_CHAT_ID',
  MIGRATE_FROM_CHAT_ID = 'MIGRATE_FROM_CHAT_ID',
  PINNED_MESSAGE = 'PINNED_MESSAGE',
  PROXIMITY_ALERT_TRIGGERED = 'PROXIMITY_ALERT_TRIGGERED',
  VIDEO_CHAT_SCHEDULED = 'VIDEO_CHAT_SCHEDULED',
  VIDEO_CHAT_STARTED = 'VIDEO_CHAT_STARTED',
  VIDEO_CHAT_ENDED = 'VIDEO_CHAT_ENDED',
  VIDEO_CHAT_PARTICIPANTS_INVITED = 'VIDEO_CHAT_PARTICIPANTS_INVITED',
  WEB_APP_DATA = 'WEB_APP_DATA',

  // Telegram Premium
  PREMIUM_GIFT = 'PREMIUM_GIFT',

  // Custom для AWE
  ENCRYPTED_MEDIA = 'ENCRYPTED_MEDIA',
  DISAPPEARING_MEDIA = 'DISAPPEARING_MEDIA',
}

export enum ApiChatPermission {
  SEND_MESSAGES = 'SEND_MESSAGES',
  SEND_MEDIA = 'SEND_MEDIA',
  ADD_MEMBERS = 'ADD_MEMBERS',
  REMOVE_MEMBERS = 'REMOVE_MEMBERS',
  EDIT_INFO = 'EDIT_INFO',
  PIN_MESSAGES = 'PIN_MESSAGES',
  DELETE_MESSAGES = 'DELETE_MESSAGES',
  BAN_MEMBERS = 'BAN_MEMBERS',
  MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS',
}

